"""added chat_id to messages table

Revision ID: 0aaedbc5745b
Revises: 9608d7f4a736
Create Date: 2026-01-19 17:16:31.245833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0aaedbc5745b'
down_revision: Union[str, Sequence[str], None] = '9608d7f4a736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.alter_column('messages', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###
