"""removed chat_id form messages table

Revision ID: 0c216d5136d6
Revises: a28b17818748
Create Date: 2026-01-20 16:54:38.943279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c216d5136d6'
down_revision: Union[str, Sequence[str], None] = 'a28b17818748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
