"""added chats table

Revision ID: 122939a8a7f5
Revises: 0aaedbc5745b
Create Date: 2026-01-19 21:19:46.125795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from src.core.db.models.base import MyUUID

# revision identifiers, used by Alembic.
revision: str = "122939a8a7f5"
down_revision: Union[str, Sequence[str], None] = "0aaedbc5745b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("username", mysql.VARCHAR(length=32), nullable=True),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("id", MyUUID(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chats")
    # ### end Alembic commands ###
