"""Added done project table

Revision ID: 1b819f178195
Revises: 3a45088c9afe
Create Date: 2026-01-02 17:29:30.001068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b819f178195'
down_revision: Union[str, Sequence[str], None] = '3a45088c9afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('done_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('images', sa.Column('done_project_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'images', 'done_projects', ['done_project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'done_project_id')
    op.drop_table('done_projects')
    # ### end Alembic commands ###
