"""decimal

Revision ID: 1c96324a4dd1
Revises: 9ae7907285a7
Create Date: 2026-01-04 20:16:21.107775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c96324a4dd1'
down_revision: Union[str, Sequence[str], None] = '9ae7907285a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'price',
               existing_type=sa.DECIMAL(precision=6, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
