"""added tables for tg bot

Revision ID: 15c84e1eeecb
Revises: cd0cd6b411aa
Create Date: 2026-01-27 12:05:12.532263

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


from src.core.db.models.base import MyUUID

# revision identifiers, used by Alembic.
revision: str = "15c84e1eeecb"
down_revision: Union[str, Sequence[str], None] = "cd0cd6b411aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("username", mysql.VARCHAR(length=32), nullable=True),
        sa.Column("id", MyUUID(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chats_chat_id"), "chats", ["chat_id"], unique=True)
    op.alter_column(
        "messages", "username", existing_type=mysql.VARCHAR(length=32), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages", "username", existing_type=mysql.VARCHAR(length=32), nullable=False
    )
    op.drop_index(op.f("ix_chats_chat_id"), table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###
