"""added user_name column

Revision ID: c02b0103c681
Revises: 99d28ff904bb
Create Date: 2026-01-31 19:33:04.448722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c02b0103c681"
down_revision: Union[str, Sequence[str], None] = "99d28ff904bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("user_name", mysql.VARCHAR(length=32), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "user_name")
    # ### end Alembic commands ###
