"""deleted username column

Revision ID: 99d28ff904bb
Revises: 2bdeadb3cfce
Create Date: 2026-01-31 14:43:46.341223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "99d28ff904bb"
down_revision: Union[str, Sequence[str], None] = "2bdeadb3cfce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("username", mysql.VARCHAR(length=32), nullable=True)
    )
    # ### end Alembic commands ###
