"""init

Revision ID: faf5adb331c5
Revises: 
Create Date: 2026-02-06 20:20:55.503205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from src.infra.db.models.base import MyUUID

# revision identifiers, used by Alembic.
revision: str = 'faf5adb331c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('access_token', mysql.TEXT(length=1000), nullable=True),
    sa.Column('expires_token', sa.DateTime(), nullable=True),
    sa.Column('id', MyUUID(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('chats',
    sa.Column('chat_id', mysql.BIGINT(), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('id', MyUUID(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=True)
    op.create_table('done_projects',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=32), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('id', MyUUID(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('object_type', sa.Enum('residential_house', 'country_house', 'guest_house', 'commersial_object', name='objecttype'), nullable=False),
    sa.Column('comment', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id', MyUUID(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_description', sa.String(length=255), nullable=False),
    sa.Column('pdf_urls', sa.JSON(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('id', MyUUID(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('main_image', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('project_id', MyUUID(length=16), nullable=True),
    sa.Column('done_project_id', MyUUID(length=16), nullable=True),
    sa.Column('id', MyUUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['done_project_id'], ['done_projects.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('projects')
    op.drop_table('messages')
    op.drop_table('done_projects')
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
