"""test fix: added default for done_project_id as uuid4

Revision ID: a5665d9b433c
Revises: 9fd21f310779
Create Date: 2026-01-28 02:12:27.599145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5665d9b433c'
down_revision: Union[str, Sequence[str], None] = '9fd21f310779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
