"""change: made optional uuid for projet_id in images table

Revision ID: 9fd21f310779
Revises: 15c84e1eeecb
Create Date: 2026-01-28 00:56:39.789729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9fd21f310779'
down_revision: Union[str, Sequence[str], None] = '15c84e1eeecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    op.drop_table('chats')
    op.alter_column('images', 'project_id',
               existing_type=sa.BINARY(length=16),
               nullable=True)
    op.alter_column('messages', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('images', 'project_id',
               existing_type=sa.BINARY(length=16),
               nullable=False)
    op.create_table('chats',
    sa.Column('chat_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=True)
    # ### end Alembic commands ###
