"""added admin table

Revision ID: 352b23c85a87
Revises: c75308f87805
Create Date: 2026-01-24 17:53:50.513105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '352b23c85a87'
down_revision: Union[str, Sequence[str], None] = 'c75308f87805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('expires_token', mysql.DATETIME(), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('access_token', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    # ### end Alembic commands ###
