"""changed type to json

Revision ID: 35e3a11b9f7e
Revises: 39a9bbd4dfc3
Create Date: 2026-01-10 23:59:44.444081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35e3a11b9f7e'
down_revision: Union[str, Sequence[str], None] = '39a9bbd4dfc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'pdf_urls',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'pdf_urls',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
