"""pdf_url to pdf_ulrs

Revision ID: 39a9bbd4dfc3
Revises: a30b89c31d17
Create Date: 2026-01-10 23:52:20.969098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "39a9bbd4dfc3"
down_revision: Union[str, Sequence[str], None] = "a30b89c31d17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("pdf_urls", sa.Text(), nullable=True))
    op.drop_column("projects", "pdf_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("pdf_url", mysql.TEXT(), nullable=True))
    op.drop_column("projects", "pdf_urls")
    # ### end Alembic commands ###
