"""Made url optional

Revision ID: 6fb1e594b23f
Revises: 89a091305c24
Create Date: 2026-01-10 05:49:22.983099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6fb1e594b23f'
down_revision: Union[str, Sequence[str], None] = '89a091305c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'url',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'url',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
