"""made uniqui

Revision ID: 7c8e9a25a417
Revises: 0c216d5136d6
Create Date: 2026-01-20 20:26:40.077118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8e9a25a417'
down_revision: Union[str, Sequence[str], None] = '0c216d5136d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    # ### end Alembic commands ###
