"""decimal

Revision ID: 9ae7907285a7
Revises: 
Create Date: 2026-01-04 20:12:32.974896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae7907285a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('done_projects',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BINARY(length=16), server_default=sa.text('(UUID_TO_BIN(UUID()))'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('price_description', sa.String(length=255), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('id', sa.BINARY(length=16), server_default=sa.text('(UUID_TO_BIN(UUID()))'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_main_image', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.BINARY(length=16), nullable=True),
    sa.Column('done_project_id', sa.BINARY(length=16), nullable=True),
    sa.Column('id', sa.BINARY(length=16), server_default=sa.text('(UUID_TO_BIN(UUID()))'), nullable=False),
    sa.ForeignKeyConstraint(['done_project_id'], ['done_projects.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('projects')
    op.drop_table('done_projects')
    # ### end Alembic commands ###
