"""added public attribut

Revision ID: da3500f50c3f
Revises: 9608d7f4a736
Create Date: 2026-01-21 01:24:39.232483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3500f50c3f'
down_revision: Union[str, Sequence[str], None] = '9608d7f4a736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('done_projects', sa.Column('public', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'public')
    op.drop_column('done_projects', 'public')
    # ### end Alembic commands ###
