"""added admin table

Revision ID: f17e41f7b17e
Revises: 352b23c85a87
Create Date: 2026-01-24 17:54:21.600691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from src.core.db.models.base import MyUUID

# revision identifiers, used by Alembic.
revision: str = "f17e41f7b17e"
down_revision: Union[str, Sequence[str], None] = "352b23c85a87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password", sa.String(length=64), nullable=False),
        sa.Column("access_token", mysql.TEXT(length=1000), nullable=True),
        sa.Column("expires_token", sa.DateTime(), nullable=True),
        sa.Column("id", MyUUID(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admins_username"), "admins", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_admins_username"), table_name="admins")
    op.drop_table("admins")
    # ### end Alembic commands ###
