"""changed from refresh to access

Revision ID: f64186a9ddfd
Revises: 45fa9a99a0da
Create Date: 2026-01-24 15:17:39.893284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f64186a9ddfd'
down_revision: Union[str, Sequence[str], None] = '45fa9a99a0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('refresh_token', mysql.CHAR(length=32), nullable=True))
    # ### end Alembic commands ###
