"""added public attr

Revision ID: 409146ea26ff
Revises: fd921a653cce
Create Date: 2026-01-24 17:42:01.571048

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "409146ea26ff"
down_revision: Union[str, Sequence[str], None] = "fd921a653cce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("done_projects", sa.Column("public", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("done_projects", "public")
    # ### end Alembic commands ###
