"""added admins table

Revision ID: cc6c36b6444e
Revises: da3500f50c3f
Create Date: 2026-01-23 12:18:07.309845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc6c36b6444e'
down_revision: Union[str, Sequence[str], None] = 'da3500f50c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('done_projects', 'public')
    op.drop_column('projects', 'public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('done_projects', sa.Column('public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
